README.md
=> Update README: Password is a keyword arg

README.md, duolingo/__init__.py
- add function **lingo.get_calendar(language_abbr=None)**
- add function **lingo.get_abbreviation_of(language)**
- add function **lingo.get_language_from_abbr(abbr)**
- update **lingo.get_languages()** function with ```abbreviations=False``` keyword parameter
If I notice any more docs that need updating I'll be sure to make another PR. Great project you have going on here, thanks for making it!
=> Add misc. functions and update docs

.gitignore, README.md, duolingo.py, duolingo/__init__.py, setup.py
Sorry about the large number of PRs containing the same commits. 
This PR contains #13 and #12  as its first three commits.
The last commit moves duolingo/__init__.py from a package to a module, where it makes a little more sense, and does a bunch of minor cleanup things, mostly to make it more readable.
=> Clean up and move from package to module

README.md, duolingo/__init__.py
One more! These are the last methods I need for the project I'm working on.
=> Add certificate and streak_info methods

README.md, duolingo.py
So. This happened.
I've rewritten the majority of the README, and added an activity stream API. This fixes #4, so you can close that after this gets merged.
Are there any other APIs that you can think of that might be wanted? I'm on a roll with this project and would be happy to contribute.
=> Add activity stream API; rewrite docs

README.md, duolingo.py
Add various APIs
update README to reflect new APIs
=> add translations, vocabulary, audio_url, related_words

.coveragerc, .gitignore, tests.py, tox.ini
It's only functional tests (unit tests must mock out the Duolingo API)
I added tox.ini for simply all and added a lint env.
=> Added functional tests with tox and coverage

duolingo.py, setup.py
I:
- replace raw ``long_description`` by README's content
- PEP8
- Moved some reference in code (version, author, etc)
- Clarify license, Apache or MIT, I put MIT everywhere
=> Improve setup.py

.travis.yml, MANIFEST.in, README.md, duolingo.py, requirements.txt, setup.py, tox.ini
Also added a ``requirements.txt``
@KartikTalwar Could you enable Travis CI for this repository ?
=> Added Travis CI

duolingo.py
@KartikTalwar, could you review ?
I do not want to write bad stuff.
=> Added docstring

duolingo.py
Just a minor change to improve code readability
=> Rename variable "word" to "topic" in get_known_words

README.md, duolingo.py
Fixed all 429 errors this time. I hope.
Changed buy streak freeze to a general function, allows buying anything from the store
Added an exception to functions that require a logged in user
=> Fixed 429 errors

README.md, duolingo.py, tests.py
A simple request that brings the user week or month leaderboard.
=> Get rank info

README.md, duolingo.py
=> add function to buy "Streak on Ice"

.gitignore, README.md, duolingo.py, tests.py
The primary goal was to just add some extra methods to slice up the language topics into more buckets. Had a need to specifically see how many "learned" skills I have left to review, as well as how many are unlearned. Also did some minor code cleanup. Please let me know if there is anything I can fix / add!
=> Add extra topic helper methods.

README.md
`get_translation` to `get_translations`
=> Readme typo fix.

README.md
I reformatted README.md so the API docs are easier to read, and to navigate.
=> Edit and format API documentation in README.md

duolingo.py
Make buy_streak_freeze() and buy_item() work again
Fix: #63
=> Fix lastest API changes in upstream

duolingo.py
Adds `get_word_definition_by_id` which will return Duolingo's dictionary entry for the given word.
=> Add method to get a word's dictionary entry

duolingo.py, tests.py
Which will be read and checked if given, and then the new jwt will be written to.
=> Adding a session_file argument to the Duolingo constructor.

duolingo.py
This is a small fix I made for myself in order to be able to get data for other users apart from the logged in one.
I saw there is a Pull Request which is working towards similar direction, but it doesn't seem active at the moment, so I am sharing this in case any one wants to use it.
=> small fix to get data for other users

CONTRIBUTING.md
Hi there :)
I wanted to make a small contribution to the project, but I couldn't easily find how to properly run the tests. I discovered and documented the thought process in a `CONTRIBUTING.md` file.
=> Add CONTRIBUTING file with development instructions

duolingo.py
See https://github.com/KartikTalwar/Duolingo/issues/94 
Sometimes the reported update time is in the future. When this is the case we use local midnight from `datetime` for filtering daily lessons.
=> Fall back on system midnight if reported update time is in the future.

.travis.yml, duolingo.py, tests.py
Seems I can set the tests on travis to run daily now, and I get emails when they fail!
So I've fixed them up, which has meant making some changes here and there to fix code.
=> Fixing up the tests, and running them daily

duolingo.py, tests.py
So that it doesn't go over Duolingo's limits as seen in #75
Closs #75
=> Adding automatic segmentation to get_translations() method.
